import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { exportKotlinStartupJson, importKotlinStartupJson, KOTLIN_STARTUP_JSON_SCHEMA_VERSION } from './kotlin-json.js';
import { DEFAULT_STARTUP_EXPERIMENT } from './experiment.js';
import { createStartupSession } from './session.js';

const KOTLIN_STARTUP_FIXTURE = fileURLToPath(new URL('./fixtures/kotlin-startup-report.json', import.meta.url));

const ELECTRON_STARTUP_FIXTURE_PATH = process.env['APS_ELECTRON_STARTUP_FIXTURE_PATH'];

function electronSession() {
  return createStartupSession({
    id: 'electron-session',
    deviceSerial: 'emulator-5554',
    packageName: 'com.example.app',
    componentName: 'com.example.app/.MainActivity',
    config: DEFAULT_STARTUP_EXPERIMENT,
    createdAtEpochMillis: 1,
    runs: [{
      id: 'run-1', sessionId: 'electron-session', iteration: 1, measured: true,
      requestedType: 'COLD', observedType: 'COLD',
      platform: { complete: true, totalTimeMs: 123, displayedTimeMs: 115 },
      warnings: ['warning'], amStartOutput: 'Status: ok', eventLogOutput: 'event',
      ttidEvidence: { source: 'EVENT_LOG', confidence: 'EXACT' },
      ttfdEvidence: { confidence: 'UNAVAILABLE', unavailableReason: 'not reported' },
    }],
  });
}

const KOTLIN_DOCUMENT = {
  schemaVersion: 1,
  summary: {},
  warnings: ['analysis warning'],
  runs: [
    {
      iteration: 7,
      runId: 'kotlin-run',
      requestedType: 'COLD',
      observedType: 'WARM',
      totalTimeMs: 123,
      thisTimeMs: 101,
      waitTimeMs: 130,
      displayedTimeMs: 115,
      fullyDrawnTimeMs: 220,
      agentAvailable: true,
      diagnostics: ['diagnostic'],
      context: {
        deviceLocalId: 'pseudonymous-device',
        packageName: 'com.example.app',
        componentName: 'com.example.app/.MainActivity',
      },
      metricEvidence: {
        ttid: { source: 'AM_START', confidence: 'EXACT' },
        ttfd: { confidence: 'UNAVAILABLE', unavailableReason: 'not reported' },
      },
      warnings: ['Warm launch observed'],
      milestones: [],
      phases: [],
      rawEvidence: { amStartOutput: 'Status: ok', eventLogOutput: 'event', compilationOutput: 'compile' },
    },
  ],
};

describe('Kotlin StartupJson v1 interchange', () => {
  it('imports the checked-in report generated by Kotlin StartupJsonExporter', () => {
    const source = readFileSync(KOTLIN_STARTUP_FIXTURE, 'utf8');
    const session = importKotlinStartupJson(source, {
      id: 'kotlin-fixture',
      capturedAtEpochMillis: 1,
      sourceFileName: 'kotlin-startup-report.json',
    });

    expect(session).toMatchObject({
      origin: 'IMPORTED',
      deviceSerial: 'IMPORTED',
      packageName: 'com.example.performance',
      componentName: 'com.example.performance/.MainActivity',
      sourceFileName: 'kotlin-startup-report.json',
    });
    expect(session.sourceDeviceLocalId).toMatch(/^[a-zA-Z0-9_-]+$/);
    expect(session.runs[0]).toEqual(expect.objectContaining({
      id: 'kotlin-startup-run-1',
      platform: expect.objectContaining({ totalTimeMs: 470, displayedTimeMs: 420, fullyDrawnTimeMs: 760 }),
      ttidEvidence: { source: 'EVENT_LOG', confidence: 'EXACT' },
      ttfdEvidence: { source: 'EVENT_LOG', confidence: 'EXACT' },
    }));
    // Rich Kotlin evidence is not silently reconstructed as empty Electron data.
    expect(exportKotlinStartupJson(session)).toBe(source);
  });

  it('does not promote a partial Kotlin context to session-wide provenance', () => {
    const session = importKotlinStartupJson(
      JSON.stringify({
        schemaVersion: 1,
        warnings: [],
        runs: [
          {
            iteration: 1,
            runId: 'contextual',
            requestedType: 'COLD',
            observedType: 'COLD',
            rawEvidence: { amStartOutput: 'Status: ok' },
            context: {
              deviceLocalId: 'pseudonymous-device',
              packageName: 'com.example.app',
              componentName: 'com.example.app/.MainActivity',
            },
          },
          {
            iteration: 2,
            runId: 'contextless',
            requestedType: 'COLD',
            observedType: 'COLD',
            rawEvidence: { amStartOutput: 'Status: ok' },
          },
        ],
      }),
      { id: 'mixed-context', capturedAtEpochMillis: 1 },
    );

    expect(session).not.toHaveProperty('packageName');
    expect(session).not.toHaveProperty('componentName');
    expect(session).not.toHaveProperty('sourceDeviceLocalId');
  });

  it('imports a Kotlin-shaped report without converting a pseudonym into an ADB serial', () => {
    const session = importKotlinStartupJson(JSON.stringify(KOTLIN_DOCUMENT), {
      id: 'imported-session',
      capturedAtEpochMillis: 1234,
      sourceFileName: 'kotlin-report.json',
    });

    expect(session).toMatchObject({
      id: 'imported-session',
      origin: 'IMPORTED',
      deviceSerial: 'IMPORTED',
      sourceDeviceLocalId: 'pseudonymous-device',
      sourceFileName: 'kotlin-report.json',
      packageName: 'com.example.app',
      componentName: 'com.example.app/.MainActivity',
    });
    expect(session.runs).toEqual([
      expect.objectContaining({
        id: 'kotlin-run',
        sessionId: 'imported-session',
        measured: true,
        requestedType: 'COLD',
        observedType: 'WARM',
        platform: expect.objectContaining({ totalTimeMs: 123, displayedTimeMs: 115, fullyDrawnTimeMs: 220 }),
        ttidEvidence: { source: 'AM_START', confidence: 'EXACT' },
        ttfdEvidence: { confidence: 'UNAVAILABLE', unavailableReason: 'not reported' },
      }),
    ]);
  });

  it('accepts Kotlin legacy reports that contain no context or metric-evidence extension', () => {
    const session = importKotlinStartupJson(
      JSON.stringify({
        schemaVersion: 1,
        warnings: [],
        runs: [{
          iteration: 1,
          runId: 'legacy',
          requestedType: 'COLD',
          observedType: 'COLD',
          displayedTimeMs: 120,
          rawEvidence: { amStartOutput: 'raw' },
        }],
      }),
      { id: 'legacy-session', capturedAtEpochMillis: 1 },
    );

    expect(session.packageName).toBeUndefined();
    expect(session.runs[0]?.ttidEvidence).toEqual({ source: 'EVENT_LOG', confidence: 'EXACT' });
    expect(session.runs[0]?.ttfdEvidence).toEqual({
      confidence: 'UNAVAILABLE',
      unavailableReason: 'The app did not call reportFullyDrawn() during this run.',
    });
  });

  it('writes the required Kotlin importer fields without serializing a live ADB serial', () => {
    const document = JSON.parse(exportKotlinStartupJson(electronSession())) as Record<string, unknown>;
    expect(document['schemaVersion']).toBe(KOTLIN_STARTUP_JSON_SCHEMA_VERSION);
    expect(document['summary']).toEqual(expect.objectContaining({ totalTime: expect.any(Object) }));
    expect(document['runs']).toEqual([expect.objectContaining({
      iteration: 1, runId: 'run-1', requestedType: 'COLD', observedType: 'COLD',
      rawEvidence: { amStartOutput: 'Status: ok', eventLogOutput: 'event', compilationOutput: null },
    })]);
    expect(JSON.stringify(document)).not.toContain('emulator-5554');
  });

  it.each([
    { schemaVersion: 2, warnings: [], runs: [] },
    { schemaVersion: 1, warnings: [], runs: [] },
    { schemaVersion: 1, warnings: [], runs: [{ iteration: 1, runId: 'x', requestedType: 'NOPE', observedType: 'COLD', rawEvidence: { amStartOutput: 'raw' } }] },
    { schemaVersion: 1, warnings: [], runs: [{ iteration: 1, runId: 'x', requestedType: 'COLD', observedType: 'COLD', rawEvidence: {} }] },
  ])('rejects malformed or unsupported Kotlin reports: %j', (document) => {
    expect(() => importKotlinStartupJson(JSON.stringify(document), { id: 'bad', capturedAtEpochMillis: 1 })).toThrow();
  });
});

if (ELECTRON_STARTUP_FIXTURE_PATH !== undefined) {
  describe('Electron StartupJson fixture writer', () => {
    it('writes the exact Kotlin-compatible report for the Kotlin importer suite', () => {
      writeFileSync(ELECTRON_STARTUP_FIXTURE_PATH, exportKotlinStartupJson(electronSession()), 'utf8');
    });
  });
}
