package com.androidperformancestudio.perfetto.capture

import com.androidperformancestudio.perfetto.model.PerfettoCaptureConfig
import com.androidperformancestudio.perfetto.model.PerfettoTraceTemplate

/** Builds a text-proto TraceConfig accepted by the Android `perfetto --txt` CLI. */
object PerfettoConfigTextBuilder {
    fun build(config: PerfettoCaptureConfig): String {
        config.customConfigText
            ?.takeIf { config.template == PerfettoTraceTemplate.CUSTOM && it.isNotBlank() }
            ?.let { return it }

        val template = templateSettings(config.template)
        val extraFtraceEvents = config.additionalCategories.filter { '/' in it }
        val extraAtraceCategories = config.additionalCategories.filterNot { '/' in it }
        val ftraceEvents = (template.ftraceEvents + extraFtraceEvents).distinct()
        val atraceCategories = (template.atraceCategories + extraAtraceCategories).distinct()

        return buildString {
            appendLine("# Perfetto trace config generated by AndroidPerformanceStudio")
            appendLine("# Template: ${config.template.displayName}")
            appendLine("# Target: ${config.targetPackage ?: "system-wide"}")
            appendLine("buffers: {")
            appendLine("  size_kb: ${config.bufferSizeKb}")
            appendLine("  fill_policy: RING_BUFFER")
            appendLine("}")
            appendLine("duration_ms: ${config.durationSeconds * 1000}")
            appendLine("flush_period_ms: 5000")

            appendLine("data_sources: {")
            appendLine("  config {")
            appendLine("    name: \"linux.ftrace\"")
            appendLine("    ftrace_config {")
            ftraceEvents.forEach { event -> appendLine("      ftrace_events: \"${escapeProtoString(event)}\"") }
            atraceCategories.forEach { category ->
                appendLine("      atrace_categories: \"${escapeProtoString(category)}\"")
            }
            config.targetPackage?.takeIf { it.isNotBlank() }?.let { targetPackage ->
                appendLine("      atrace_apps: \"${escapeProtoString(targetPackage)}\"")
            }
            appendLine("      symbolize_ksyms: true")
            appendLine("    }")
            appendLine("  }")
            appendLine("}")

            appendProcessStats(pollMemory = template.pollMemory)
            if (template.collectSystemStats) appendSystemStats()
            if (template.collectFrameTimeline) appendSimpleDataSource("android.surfaceflinger.frametimeline")
            if (template.collectInputEvents) appendInputEvents()
            appendSimpleDataSource("android.packages_list")
            if (template.collectNativeHeap) {
                config.targetPackage?.takeIf { it.isNotBlank() }?.let { appendHeapProfile(it) }
            }
        }
    }

    private fun StringBuilder.appendProcessStats(pollMemory: Boolean) {
        appendLine("data_sources: {")
        appendLine("  config {")
        appendLine("    name: \"linux.process_stats\"")
        appendLine("    process_stats_config {")
        appendLine("      scan_all_processes_on_start: true")
        appendLine("      record_thread_names: true")
        if (pollMemory) appendLine("      proc_stats_poll_ms: 1000")
        appendLine("    }")
        appendLine("  }")
        appendLine("}")
    }

    private fun StringBuilder.appendSystemStats() {
        appendLine("data_sources: {")
        appendLine("  config {")
        appendLine("    name: \"linux.sys_stats\"")
        appendLine("    sys_stats_config {")
        appendLine("      cpufreq_period_ms: 250")
        appendLine("      meminfo_period_ms: 1000")
        appendLine("      vmstat_period_ms: 1000")
        appendLine("      stat_period_ms: 1000")
        appendLine("    }")
        appendLine("  }")
        appendLine("}")
    }

    private fun StringBuilder.appendInputEvents() {
        appendLine("data_sources: {")
        appendLine("  config {")
        appendLine("    name: \"android.input.inputevent\"")
        appendLine("    android_input_event_config {")
        appendLine("      trace_dispatcher_input_events: true")
        appendLine("    }")
        appendLine("  }")
        appendLine("}")
    }

    private fun StringBuilder.appendHeapProfile(targetPackage: String) {
        appendLine("data_sources: {")
        appendLine("  config {")
        appendLine("    name: \"android.heapprofd\"")
        appendLine("    heapprofd_config {")
        appendLine("      sampling_interval_bytes: 4096")
        appendLine("      process_cmdline: \"${escapeProtoString(targetPackage)}\"")
        appendLine("    }")
        appendLine("  }")
        appendLine("}")
    }

    private fun StringBuilder.appendSimpleDataSource(name: String) {
        appendLine("data_sources: {")
        appendLine("  config {")
        appendLine("    name: \"$name\"")
        appendLine("  }")
        appendLine("}")
    }

    private fun escapeProtoString(value: String): String = value.replace("\\", "\\\\").replace("\"", "\\\"")

    private fun templateSettings(template: PerfettoTraceTemplate): TemplateSettings =
        when (template) {
            PerfettoTraceTemplate.SYSTEM_OVERVIEW ->
                TemplateSettings(
                    ftraceEvents =
                        listOf(
                            "sched/sched_switch",
                            "sched/sched_waking",
                            "sched/sched_wakeup",
                            "sched/sched_wakeup_new",
                            "sched/sched_blocked_reason",
                            "power/cpu_frequency",
                            "power/cpu_idle",
                            "binder/binder_transaction",
                            "binder/binder_transaction_received",
                        ),
                    atraceCategories = listOf("am", "binder_driver", "gfx", "view", "wm", "power"),
                    collectFrameTimeline = true,
                    collectSystemStats = true,
                    pollMemory = true,
                )
            PerfettoTraceTemplate.APP_PERFORMANCE ->
                TemplateSettings(
                    ftraceEvents =
                        listOf(
                            "sched/sched_switch",
                            "sched/sched_waking",
                            "sched/sched_wakeup_new",
                            "binder/binder_transaction",
                            "binder/binder_transaction_received",
                        ),
                    atraceCategories = listOf("am", "binder_driver", "gfx", "view", "wm"),
                    collectFrameTimeline = true,
                    collectSystemStats = true,
                )
            PerfettoTraceTemplate.GFX_PIPELINE ->
                TemplateSettings(
                    ftraceEvents = listOf("sched/sched_switch", "sched/sched_waking", "power/cpu_frequency"),
                    atraceCategories = listOf("gfx", "view", "wm"),
                    collectFrameTimeline = true,
                    collectSystemStats = true,
                )
            PerfettoTraceTemplate.INPUT_LATENCY ->
                TemplateSettings(
                    ftraceEvents =
                        listOf(
                            "sched/sched_switch",
                            "sched/sched_waking",
                            "sched/sched_wakeup_new",
                            "binder/binder_transaction",
                            "binder/binder_transaction_received",
                        ),
                    atraceCategories = listOf("input", "view", "wm"),
                    collectInputEvents = true,
                )
            PerfettoTraceTemplate.MEMORY_PROFILE ->
                TemplateSettings(
                    ftraceEvents =
                        listOf(
                            "sched/sched_switch",
                            "kmem/rss_stat",
                            "mm_event/mm_event_record",
                            "oom/oom_score_adj_update",
                            "lowmemorykiller/lowmemory_kill",
                        ),
                    atraceCategories = listOf("am", "dalvik"),
                    collectSystemStats = true,
                    pollMemory = true,
                    collectNativeHeap = true,
                )
            PerfettoTraceTemplate.CUSTOM -> TemplateSettings()
        }

    private data class TemplateSettings(
        val ftraceEvents: List<String> = emptyList(),
        val atraceCategories: List<String> = emptyList(),
        val collectFrameTimeline: Boolean = false,
        val collectSystemStats: Boolean = false,
        val pollMemory: Boolean = false,
        val collectInputEvents: Boolean = false,
        val collectNativeHeap: Boolean = false,
    )
}
