import { contextBridge, ipcRenderer } from 'electron';
import {
  IPC_CHANNELS,
  type ApsApi,
  type AiConfigurationInput,
  type ApplicationUiSettingsPatch,
  type BatteryCaptureInput,
  type BenchmarkCompareInput,
  type CpuCaptureRequest,
  type CpuSnapshotRequest,
  type MethodCaptureRequest,
  type AiAnalyzeRequest,
  type MethodSnapshotRequest,
  type SourceResolveRequest,
  type FrameCaptureInput,
  type BitmapCaptureRequest,
  type MemoryCaptureInput,
  type MemoryInstanceDetailRequest,
  type MemoryInstanceRequest,
  type NativeHeapCaptureRequest,
  type StartupCaptureInput,
  type TraceCaptureInput,
} from '../shared/ipc.js';

const api: ApsApi = {
  getShellSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.shellSnapshot),
  updateSettings: (patch: ApplicationUiSettingsPatch) => ipcRenderer.invoke(IPC_CHANNELS.updateSettings, patch),
  chooseAndroidSdkDirectory: () => ipcRenderer.invoke(IPC_CHANNELS.chooseAndroidSdkDirectory),
  refreshDevices: () => ipcRenderer.invoke(IPC_CHANNELS.refreshDevices),
  openDestination: (destination) => ipcRenderer.invoke(IPC_CHANNELS.openDestination, destination),
  getTraceAnalyzer: () => ipcRenderer.invoke(IPC_CHANNELS.traceAnalyzer),
  captureTrace: (input: TraceCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.traceCapture, input),
  openTraceInAnalyzer: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.traceOpen, id),
  openPublicPerfettoUi: () => ipcRenderer.invoke(IPC_CHANNELS.traceOpenPublicUi),
  revealTrace: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.traceReveal, id),
  captureLayout: (serial: string) => ipcRenderer.invoke(IPC_CHANNELS.layoutCapture, serial),
  listLayoutCaptures: () => ipcRenderer.invoke(IPC_CHANNELS.layoutList),
  loadLayoutCapture: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.layoutLoad, id),
  captureFrame: (input: FrameCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.frameCapture, input),
  listFrameSessions: () => ipcRenderer.invoke(IPC_CHANNELS.frameList),
  loadFrameSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.frameLoad, id),
  captureStartup: (input: StartupCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.startupCapture, input),
  listStartupSessions: () => ipcRenderer.invoke(IPC_CHANNELS.startupList),
  loadStartupSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.startupLoad, id),
  captureBattery: (input: BatteryCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.batteryCapture, input),
  listBatterySessions: () => ipcRenderer.invoke(IPC_CHANNELS.batteryList),
  loadBatterySession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.batteryLoad, id),
  importNetworkHar: () => ipcRenderer.invoke(IPC_CHANNELS.networkImport),
  listNetworkSessions: () => ipcRenderer.invoke(IPC_CHANNELS.networkList),
  loadNetworkSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.networkLoad, id),
  importBenchmarkRun: () => ipcRenderer.invoke(IPC_CHANNELS.benchmarkImport),
  listBenchmarkRuns: () => ipcRenderer.invoke(IPC_CHANNELS.benchmarkList),
  compareBenchmarkRuns: (input: BenchmarkCompareInput) => ipcRenderer.invoke(IPC_CHANNELS.benchmarkCompare, input),
  getAgiStatus: () => ipcRenderer.invoke(IPC_CHANNELS.gpuStatus),
  launchAgi: () => ipcRenderer.invoke(IPC_CHANNELS.gpuLaunch),
  importGpuArtifact: () => ipcRenderer.invoke(IPC_CHANNELS.gpuImport),
  listGpuArtifacts: () => ipcRenderer.invoke(IPC_CHANNELS.gpuList),
  openGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuOpen, id),
  revealGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuReveal, id),
  relocateGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuRelocate, id),
  importTraceFromPath: (path: string) => ipcRenderer.invoke(IPC_CHANNELS.traceImportFromPath, path),
  listSourceWorkspaces: () => ipcRenderer.invoke(IPC_CHANNELS.sourceList),
  addSourceWorkspace: () => ipcRenderer.invoke(IPC_CHANNELS.sourceAdd),
  removeSourceWorkspace: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.sourceRemove, id),
  reindexSourceWorkspace: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.sourceReindex, id),
  searchSourceSymbols: (input: { workspaceId: string; query: string; limit: number }) =>
    ipcRenderer.invoke(IPC_CHANNELS.sourceSearch, input),
  resolveSourceEvidence: (input: SourceResolveRequest) => ipcRenderer.invoke(IPC_CHANNELS.sourceResolve, input),
  readSourceFile: (input: { workspaceId: string; relativePath: string }) =>
    ipcRenderer.invoke(IPC_CHANNELS.sourceRead, input),
  setSourceAiUpload: (input: { workspaceId: string; allowed: boolean }) =>
    ipcRenderer.invoke(IPC_CHANNELS.sourceSetAiUpload, input),
  captureMethodRecording: (input: MethodCaptureRequest) => ipcRenderer.invoke(IPC_CHANNELS.methodCapture, input),
  listMethodSessions: () => ipcRenderer.invoke(IPC_CHANNELS.methodList),
  methodSnapshot: (input: MethodSnapshotRequest) => ipcRenderer.invoke(IPC_CHANNELS.methodSnapshot, input),
  removeMethodSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.methodRemove, id),
  captureCpuProfile: (input: CpuCaptureRequest) => ipcRenderer.invoke(IPC_CHANNELS.cpuCapture, input),
  importCpuProfile: () => ipcRenderer.invoke(IPC_CHANNELS.cpuImport),
  listCpuProfiles: () => ipcRenderer.invoke(IPC_CHANNELS.cpuList),
  cpuSnapshot: (input: CpuSnapshotRequest) => ipcRenderer.invoke(IPC_CHANNELS.cpuSnapshot, input),
  removeCpuProfile: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.cpuRemove, id),
  captureMemory: (input: MemoryCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.memoryCapture, input),
  listMemorySessions: () => ipcRenderer.invoke(IPC_CHANNELS.memoryList),
  loadMemorySession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.memoryLoad, id),
  queryMemoryInstances: (input: MemoryInstanceRequest) =>
    ipcRenderer.invoke(IPC_CHANNELS.memoryInstances, input),
  memoryInstanceDetail: (input: MemoryInstanceDetailRequest) =>
    ipcRenderer.invoke(IPC_CHANNELS.memoryInstanceDetail, input),
  captureBitmapDump: (input: BitmapCaptureRequest) => ipcRenderer.invoke(IPC_CHANNELS.bitmapCapture, input),
  listBitmapSessions: () => ipcRenderer.invoke(IPC_CHANNELS.bitmapList),
  loadBitmapSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.bitmapLoad, id),
  removeBitmapSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.bitmapRemove, id),
  captureNativeHeap: (input: NativeHeapCaptureRequest) => ipcRenderer.invoke(IPC_CHANNELS.nativeHeapCapture, input),
  listNativeHeapSessions: () => ipcRenderer.invoke(IPC_CHANNELS.nativeHeapList),
  loadNativeHeapSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.nativeHeapLoad, id),
  removeNativeHeapSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.nativeHeapRemove, id),
  getAiSettings: () => ipcRenderer.invoke(IPC_CHANNELS.aiSettings),
  saveAiConfiguration: (input: AiConfigurationInput) => ipcRenderer.invoke(IPC_CHANNELS.aiSaveConfiguration, input),
  saveAiCredential: (value: string) => ipcRenderer.invoke(IPC_CHANNELS.aiSaveCredential, value),
  clearAiCredential: () => ipcRenderer.invoke(IPC_CHANNELS.aiClearCredential),
  listAiModels: () => ipcRenderer.invoke(IPC_CHANNELS.aiModels),
  analyzeLayoutWithAi: (input: AiAnalyzeRequest) => ipcRenderer.invoke(IPC_CHANNELS.aiAnalyze, input),
  listAiSessions: () => ipcRenderer.invoke(IPC_CHANNELS.aiSessions),
  loadAiFindings: (sessionId: string) => ipcRenderer.invoke(IPC_CHANNELS.aiFindings, sessionId),
};

contextBridge.exposeInMainWorld('aps', api);
