import { contextBridge, ipcRenderer } from 'electron';
import {
  IPC_CHANNELS,
  type ApsApi,
  type ApplicationUiSettingsPatch,
  type BatteryCaptureInput,
  type BenchmarkCompareInput,
  type CpuCaptureRequest,
  type CpuSnapshotRequest,
  type FrameCaptureInput,
  type MemoryCaptureInput,
  type StartupCaptureInput,
  type TraceCaptureInput,
} from '../shared/ipc.js';

const api: ApsApi = {
  getShellSnapshot: () => ipcRenderer.invoke(IPC_CHANNELS.shellSnapshot),
  updateSettings: (patch: ApplicationUiSettingsPatch) => ipcRenderer.invoke(IPC_CHANNELS.updateSettings, patch),
  refreshDevices: () => ipcRenderer.invoke(IPC_CHANNELS.refreshDevices),
  openDestination: (destination) => ipcRenderer.invoke(IPC_CHANNELS.openDestination, destination),
  getTraceAnalyzer: () => ipcRenderer.invoke(IPC_CHANNELS.traceAnalyzer),
  captureTrace: (input: TraceCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.traceCapture, input),
  openTraceInAnalyzer: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.traceOpen, id),
  openPublicPerfettoUi: () => ipcRenderer.invoke(IPC_CHANNELS.traceOpenPublicUi),
  revealTrace: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.traceReveal, id),
  captureLayout: (serial: string) => ipcRenderer.invoke(IPC_CHANNELS.layoutCapture, serial),
  listLayoutCaptures: () => ipcRenderer.invoke(IPC_CHANNELS.layoutList),
  loadLayoutCapture: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.layoutLoad, id),
  captureFrame: (input: FrameCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.frameCapture, input),
  listFrameSessions: () => ipcRenderer.invoke(IPC_CHANNELS.frameList),
  loadFrameSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.frameLoad, id),
  captureStartup: (input: StartupCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.startupCapture, input),
  listStartupSessions: () => ipcRenderer.invoke(IPC_CHANNELS.startupList),
  loadStartupSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.startupLoad, id),
  captureBattery: (input: BatteryCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.batteryCapture, input),
  listBatterySessions: () => ipcRenderer.invoke(IPC_CHANNELS.batteryList),
  loadBatterySession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.batteryLoad, id),
  importNetworkHar: () => ipcRenderer.invoke(IPC_CHANNELS.networkImport),
  listNetworkSessions: () => ipcRenderer.invoke(IPC_CHANNELS.networkList),
  loadNetworkSession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.networkLoad, id),
  importBenchmarkRun: () => ipcRenderer.invoke(IPC_CHANNELS.benchmarkImport),
  listBenchmarkRuns: () => ipcRenderer.invoke(IPC_CHANNELS.benchmarkList),
  compareBenchmarkRuns: (input: BenchmarkCompareInput) => ipcRenderer.invoke(IPC_CHANNELS.benchmarkCompare, input),
  getAgiStatus: () => ipcRenderer.invoke(IPC_CHANNELS.gpuStatus),
  launchAgi: () => ipcRenderer.invoke(IPC_CHANNELS.gpuLaunch),
  importGpuArtifact: () => ipcRenderer.invoke(IPC_CHANNELS.gpuImport),
  listGpuArtifacts: () => ipcRenderer.invoke(IPC_CHANNELS.gpuList),
  openGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuOpen, id),
  revealGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuReveal, id),
  relocateGpuArtifact: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.gpuRelocate, id),
  importTraceFromPath: (path: string) => ipcRenderer.invoke(IPC_CHANNELS.traceImportFromPath, path),
  captureCpuProfile: (input: CpuCaptureRequest) => ipcRenderer.invoke(IPC_CHANNELS.cpuCapture, input),
  listCpuProfiles: () => ipcRenderer.invoke(IPC_CHANNELS.cpuList),
  cpuSnapshot: (input: CpuSnapshotRequest) => ipcRenderer.invoke(IPC_CHANNELS.cpuSnapshot, input),
  removeCpuProfile: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.cpuRemove, id),
  captureMemory: (input: MemoryCaptureInput) => ipcRenderer.invoke(IPC_CHANNELS.memoryCapture, input),
  listMemorySessions: () => ipcRenderer.invoke(IPC_CHANNELS.memoryList),
  loadMemorySession: (id: string) => ipcRenderer.invoke(IPC_CHANNELS.memoryLoad, id),
};

contextBridge.exposeInMainWorld('aps', api);
