#!/usr/bin/env bash
set -euo pipefail

readonly PINNED_TOOLS_BASE_COMMIT="b1261356012800c0a93d18f03b060024e8162c2f"
readonly REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
readonly AOSP_ROOT="${1:?usage: $0 AOSP_ROOT OUTPUT_DIR}"
readonly OUTPUT_DIR="${2:?usage: $0 AOSP_ROOT OUTPUT_DIR}"
readonly TOOLS_BASE="$AOSP_ROOT/tools/base"
readonly PATCH="$REPO_ROOT/third_party/aosp-ui-inspector-patches/0001-require-session-token.patch"
patched=false
cleanup() {
  if [[ "$patched" == true ]]; then
    (cd "$TOOLS_BASE/ui-inspector" && patch -R -p1 < "$PATCH") >/dev/null
  fi
}
trap cleanup EXIT

[[ "$(git -C "$TOOLS_BASE" rev-parse HEAD)" == "$PINNED_TOOLS_BASE_COMMIT" ]] || {
  echo "tools/base must be at $PINNED_TOOLS_BASE_COMMIT" >&2
  exit 1
}
[[ -z "$(git -C "$TOOLS_BASE" status --porcelain)" ]] || {
  echo "tools/base checkout must be clean (the security patch is applied during this build)" >&2
  exit 1
}

(cd "$TOOLS_BASE/ui-inspector" && patch -p1 < "$PATCH")
patched=true
"$TOOLS_BASE/bazel/bazel" build \
  //tools/base/ui-inspector/agent/native:lib_ui_inspector_agent.so \
  //tools/base/ui-inspector/agent/service:lib_ui_inspector_service \
  //tools/base/ui-inspector/agent/payload:lib_ui_inspector_payload \
  //tools/base/ui-inspector/agent/inspectors/view:view_inspector_jar

mkdir -p "$OUTPUT_DIR/agent/armeabi-v7a" "$OUTPUT_DIR/agent/arm64-v8a" "$OUTPUT_DIR/agent/x86_64"

copy_unique() {
  local pattern="$1" destination="$2"
  local matches count source
  matches="$(find "$AOSP_ROOT/bazel-bin/tools/base/ui-inspector" -type f -path "$pattern")"
  count="$(printf '%s\n' "$matches" | sed '/^$/d' | wc -l | tr -d ' ')"
  [[ "$count" == 1 ]] || {
    printf 'Expected one build output for %s, found %s\n' "$pattern" "$count" >&2
    exit 1
  }
  source="$matches"
  cp "$source" "$destination"
}

for abi in armeabi-v7a arm64-v8a x86_64; do
  copy_unique "*/native/*/$abi/lib_ui_inspector_agent.so" "$OUTPUT_DIR/agent/$abi/lib_ui_inspector_agent.so"
done
copy_unique "*/service/lib_ui_inspector_service.jar" "$OUTPUT_DIR/lib_ui_inspector_service.jar"
copy_unique "*/payload/lib_ui_inspector_payload.jar" "$OUTPUT_DIR/lib_ui_inspector_payload.jar"
copy_unique "*/inspectors/view/view-inspector.jar" "$OUTPUT_DIR/view-inspector.jar"

for jar in "$OUTPUT_DIR"/*.jar; do
  unzip -l "$jar" | grep -q 'classes.dex' || {
    echo "$jar is not a dexed inspector artifact" >&2
    exit 1
  }
done

sha256() { shasum -a 256 "$1" | awk '{print $1}'; }
cat > "$OUTPUT_DIR/manifest.properties" <<EOF
agent.armeabi-v7a.sha256=$(sha256 "$OUTPUT_DIR/agent/armeabi-v7a/lib_ui_inspector_agent.so")
agent.arm64-v8a.sha256=$(sha256 "$OUTPUT_DIR/agent/arm64-v8a/lib_ui_inspector_agent.so")
agent.x86_64.sha256=$(sha256 "$OUTPUT_DIR/agent/x86_64/lib_ui_inspector_agent.so")
service.sha256=$(sha256 "$OUTPUT_DIR/lib_ui_inspector_service.jar")
payload.sha256=$(sha256 "$OUTPUT_DIR/lib_ui_inspector_payload.jar")
view.sha256=$(sha256 "$OUTPUT_DIR/view-inspector.jar")
EOF
cat > "$OUTPUT_DIR/PROVENANCE.md" <<EOF
# Compose inspection agent bundle

- AOSP tools/base commit: \`$PINNED_TOOLS_BASE_COMMIT\`
- APS patch: \`third_party/aosp-ui-inspector-patches/0001-require-session-token.patch\`
- Generated by: \`tools/build-compose-agent-bundle.sh\`

The bundle contains only the three supported Android ABIs and the patched,
dexed service, payload, and View inspector. Runtime code verifies every hash in
\`manifest.properties\` before authorization or injection.
EOF

echo "Verified Compose agent bundle written to $OUTPUT_DIR"
